name: village_app
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.9
  path_provider: ^2.0.9 
  flutter_animate: ^4.5.0
  http: ^1.2.1
  intl: ^0.18.0
  provider: ^6.1.2
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.9.2

  # Add other dependencies here if needed

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The following line prevents the `flutter pub get` command from
  # automatically running `flutter packages get` and `flutter pub get`
  # on all the example projects, which can take a long time.
  # Uncomment it if you're developing on a slow network or on a very slow machine.
  # avoid-using-full-package-names: true

flutter:
  uses-material-design: true
  assets:
    - assets\images\user.jpg
    - assets\images\icon.png
    - assets\images\bg1.png
    - assets\images\bg2.png
    - assets\images\bg.jpg
    - assets\images\admin.png
    - assets\images\user.png
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets\fonts\PlusJakartaSans-Bold.ttf
        - asset: assets\fonts\PlusJakartaSans-Regular.ttf
          weight: 700